### ISSUE TITLE
msw.CouplerMapping should evaluate the well package only if msw.Sprinkling class is present

### ISSUE THREAD

**Issue by HendrikKok** [Deltares/imod-python#1056]
When generating the coupled id's, the well package is evaluated to look for groundwater extraction nodes. If after generating the MetaSWAP model, the msw.Sprinkling package is popped from the model, the coupling still includes the sprinkling nodes. Since the corresponding sprinkling input is not generated, this results in MetaSWAP errors.  

A more robust method would be to evaluate the well package only when Sprinkling package is present in model.

**Comment by Huite** [comment]
Doesn't this belong in primod, in the imod-coupler repo instead?
(The code is currently duplicated and share between here and there, I think)

**Comment by JoerivanEngelen** [comment]
This PR #1259 fixes this in a different way: CouplerMappings are generated upon writing the model, therefore this wouldn't be an issue anymore.
