### ISSUE TITLE
average well rate timeseries.

### ISSUE THREAD

**Issue by luitjansl** [Deltares/imod-python#1068]
Whether to modify `create_time_discretization` or create an extra method which enforces timesteps for wells.  
Might be able to use pandas resampling functionality: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.resample.html.

**Comment by luitjansl** [comment]
-options: 
1) enforce time discretization of wells on import from imod5 data by passing a list of calculation times (or a time discretization object)
2) import as is, and adjust the time series later in a separate command

we choose option 1 because option 2 would lead to a very large dataset:  all the wells could have different time points, and all would be present in all wells but filled with Nan's.

**Comment by JoerivanEngelen** [comment]
I discussed with Peter, apparently times are aggregated by computing a time-duration-weighted mean, which is the same as integration in this case, as the well rates are defined as block function.
