### ISSUE TITLE
import chd packages from imod5

### ISSUE THREAD

**Issue by luitjansl** [Deltares/imod-python#1087]
previousy in #966 a chd package was imported from locations where ibound < 0. 
But apart from that, we must also import chd packages explicitly declared in the input data.

**Comment by JoerivanEngelen** [comment]
We just discovered that this issue is duplicate. CHD cells are only defined on places where ibound < 0.

See this comment: https://github.com/Deltares/imod-python/pull/1069#issuecomment-2191200812
