### ISSUE TITLE
`_create_dataarray_from_values` in imod.prj should not allocate eagerly

### ISSUE THREAD

**Issue by Huite** [Deltares/imod-python#1143]
I remember @HendrikKok complaining that reading a project file was demanding a massive amount of memory.

I think it's due to this function:

```python
def _create_dataarray_from_values(values: List[float], headers: List[Dict[str, Any]]):
    coords = _merge_coords(headers)
    firstdims = headers[0]["dims"]
    shape = [len(coord) for coord in coords.values()]
    da = xr.DataArray(np.reshape(values, shape), dims=firstdims, coords=coords)
    return da
```

https://github.com/Deltares/imod-python/blob/b65e6bf077e9db9c87014f443d8b5345df448d0a/imod/formats/prj/prj.py#L533

`np.reshape(values, shape)` is allocating eagerly. I'm now left wondering whether this creates problems.

It's possible data is coming in as both constant scalar values, and IDFs. In that case, they have to be merged to a single entity:

```python
        dap = _create_datarray_from_paths(paths_valid, headers_paths)
        dav = _create_dataarray_from_values(values_valid, headers_values)
        dap.name = "tmp"
        dav.name = "tmp"
        da = xr.merge((dap, dav), join="outer")["tmp"]
```

However, looking at the code above: the result of `_create_dataarray_from_values` should be a 1D array; the broadcasting by `merge` should take care of the additional dimensions. I thought the merge here would be delayed, dask could just store all the values in the task DAG.
If this isn't the case, this results in massive arrays being here.

Regardless, it's a good idea to have both functions behaving consistently, that is: they should return DataArrays with dask data, not numpy data.

This would do the trick:

```python
import dask.array

...

def _create_dataarray_from_values(values: List[float], headers: List[Dict[str, Any]]):
    coords = _merge_coords(headers)
    firstdims = headers[0]["dims"]
    shape = [len(coord) for coord in coords.values()]
    data = dask.array.reshape(dask.array.array(values), shape)
    da = xr.DataArray(data=data, dims=firstdims, coords=coords)
    return da
```

Regardless, I recommend tracking down Hendrik's case, and seeing whether this solves anything.
Step through the code with the debugger and keep an eye on the memory allocated when the `xr.merge` is called.

**Comment by JoerivanEngelen** [comment]
Related to https://github.com/Deltares/imod-python/issues/845

**Comment by Huite** [comment]
Duplicate, closing in favor of #845
