### ISSUE TITLE
Change to default pydata-sphinx-theme 

### ISSUE THREAD

**Issue by JoerivanEngelen** [Deltares/imod-python#1150]
Due to some update in the environment, tables look quite bad now in the development version of our documentation. Luckily, online it still looks OK, because the last release environment didn't have these changes yet. This is because we created a custom template, which takes some work every now and then to keep afloat with every update of pydata-sphinx-theme or some of its dependencies.

![image](https://github.com/user-attachments/assets/b155b8cb-8712-4a5a-aa76-5953e9f82865)

I assumed freezing the pydata-sphinx theme and sphinx would be enough to keep the custom theme stable, but apparently it isn't. Probably better to also move to the default pydata-sphinx-theme, as that requires a lot less maintenance. This is also what xugrid and hydroMT did. Or we could move to Quarto, but that is a lot of more work.

**Comment by Huite** [comment]
Just move to the default theme for now. I will argue that sphinx still makes good sense for Python package docs because rST has good support for local directives such as :class:, :meth:, etc.

**Comment by JoerivanEngelen** [comment]
Yeah, the Quartodoc project might be able to help out with that https://github.com/machow/quartodoc/tree/main I'm looking at that repo every so often, the seems very active from what I can tell.

**Comment by Huite** [comment]
Still looks quite a bit worse though?

See:
https://deltares.github.io/Ribasim/reference/python/Model.html#ribasim.Model
