### ISSUE TITLE
fix metaswap regridding branch after merging master

### ISSUE THREAD

**Issue by luitjansl** [Deltares/imod-python#1152]
after  a merge from master, the metaswap regridding branch needs a fix to make metaswap regridding tests pass. Metaswap does not have the RegridderMethodType dataclass yet, so its regridding method data is still a dictionary. 
This PR implements RegridderMethodType dataclasses for metaswap, and moves some base classes used for regridding to imod.utils (they were in imod/mf6before)

**Comment by JoerivanEngelen** [comment]
Fixed in #1153
