### ISSUE TITLE
API reference: namespacing is confusing

### ISSUE THREAD

**Issue by Huite** [Deltares/imod-python#1236]
As mentioned by @VermeulenPTM:

The handwritten API reference shows: 
![image](https://github.com/user-attachments/assets/2131789c-1969-43ff-8d62-f6599e015953)

However, the individual method shows:

![image](https://github.com/user-attachments/assets/d4e77cfc-eaf3-41c6-9728-894d0cacce3c)

So there's a discrepancy between `imod.idf.open` and `imod.formats.idf.open`.

I did a little checking, e.g. xarray has the same for e.g. the groupby objects: (https://docs.xarray.dev/en/stable/generated/xarray.core.groupby.DatasetGroupBy.html#xarray.core.groupby.DatasetGroupBy).html#xarray.core.groupby.DatasetGroupBy

**Comment by Huite** [comment]
Somewhat to my surprise, this only shows up in the I/O methods for us.

My current explanation is that for all the other namespaces, we are importing individual function/classes (i.e. Python objects) via `from imod.prepare.regridder import Regridder` versus a module via `from imod.formats import idf`.

**Comment by Huite** [comment]
I've spent roughly an hour in the train on this, with very little to show for it. It is not at all straightforward to configure sphinx here; by far the most straightforward solution is to promote the different format namespaces, i.e. actually making an imod/idf module (which in turn can be a file or a directory with an __init__). That feels a bit overblown just for documentation.

I see there are some custom templates (why?), perhaps adding a special one for these formats is the most straightforward solution...

Won't fix is valid too...

**Comment by JoerivanEngelen** [comment]
Yeah this is something that bugged me a bit as well, but I never pursued looking for a fix.
Thanks for going through the efforts of trying to find something.

I go for a won't fix, we can re-open or create a new issue if something good pops up.
