### ISSUE TITLE
mf6.open_cbc: FRF and FFF are swapped in case a model has only one column

### ISSUE THREAD

**Issue by HendrikKok** [Deltares/imod-python#1242]
In case a model has one column and multiple rows, the flux-ja-face conversion to FRF, FFF goes wrong in the dis_indices method. 

For this case the + 1 node does not correspond to the right neighbor but the front one. Since the + 1 and + ncol evaluation are both true, the order of evaluation causes the swap to FRF. 

Should be solved by evaluating d == 1 & ncol != 1

**Comment by JoerivanEngelen** [comment]
If I'm not mistaken, this issue previously popped up in https://github.com/Deltares/imod-python/issues/159 ?

**Comment by Huite** [comment]
Indeed, that can then be closed.
