### ISSUE TITLE
Hypothesis imod.tests.test_msw.test_grid_data test_write failure

### ISSUE THREAD

**Issue by Huite** [Deltares/imod-python#1251]
See results on this commit https://github.com/Deltares/imod-python/pull/1250/commits/2bc4b28f8d0f7194125bb737732570eb80e97f95

```
hypothesis.errors.FlakyFailure: Hypothesis test_write(fixed_format_parser=function, area=1.175494351e-38, landuse=1.0001511807653025, rootzone_depth=9.073467254638674, surface_elevation=0.3333333333333333, soil_physical_unit=999999.0) produces unreliable results: Falsified on the first call but did not on a subsequent one (1 sub-exception)
Falsifying example: test_write(
    fixed_format_parser=function,
    area=1.175494351e-38,
    landuse=1.0001511807653025,
    rootzone_depth=9.073467254638674,
    surface_elevation=0.3333333333333333,
    soil_physical_unit=999999.0,
)
```

Might be worth investigating whether this is can be replicated, and whether it's something to pick up.

**Comment by Huite** [comment]
Just sluggishness of the TeamCity agent. Closing.

**Comment by JoerivanEngelen** [comment]
Error message is quite clear: ``hypothesis.errors.DeadlineExceeded: Test took 834.76ms, which exceeds the deadline of 400.00ms``

This happens every so often, on a slow agent.
