### ISSUE TITLE
Support HFB with xarray >=2024.10.0

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#1271]
Xarray has been fixed to version 2024.09.0 due to failing unittests.
There seems to be 2 kinds of errors
- to_netcdf stopped working
- deepcopy of the clip utility failed when applied to a model with a hfb

**Link to failing build**
https://dpcbuild.deltares.nl/buildConfiguration/iMOD6_IMODPython_Windows_Tests/5025998?buildTab=overview&expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true&expandBuildProblemsSection=false&expandPull+Request+Details=true

**LogFile:**
[Windows_UnitTests_1203.log.zip](https://github.com/user-attachments/files/17618027/Windows_UnitTests_1203.log.zip)

**Comment by JoerivanEngelen** [comment]
To add to this:

If I'm not mistaken, we stored HFB packages in netcdfs as shapely or geopandas data in NetCDFs, this is causing errors with to_netcdf now.

**Comment by JoerivanEngelen** [comment]
Update: This issue falsely reported dask was at fault, but it was xarray which has been set to avoid 2024.10.0. I therefore took the liberty of altering the title of this issue. Dask works fine, for example see https://github.com/Deltares/imod-python/pull/1280

**Comment by Manangka** [comment]
This has bee addressed in #1327
