### ISSUE TITLE
Modflow6Simulation.from_imod5_data does not work with HFB

### ISSUE THREAD

**Issue by WouterSwierstra** [Deltares/imod-python#1322]
**Bug description**
Modflow6Simulation.from_imod5_data does not work if there is HFB package in PRJ file.

**Steps to reproduce**
1. What error message do you get?

Traceback (most recent call last):
  File "c:\data\projdirs\iMOD-Suite-tutorial_03\.pixi\envs\default\Lib\site-packages\xarray\core\extension_array.py", line 112, in __getattr__
    return getattr(self.array, attr)
                   ^^^^^^^^^^
  File "c:\data\projdirs\iMOD-Suite-tutorial_03\.pixi\envs\default\Lib\site-packages\xarray\core\extension_array.py", line 112, in __getattr__
    return getattr(self.array, attr)
                   ^^^^^^^^^^
  File "c:\data\projdirs\iMOD-Suite-tutorial_03\.pixi\envs\default\Lib\site-packages\xarray\core\extension_array.py", line 112, in __getattr__
    return getattr(self.array, attr)
                   ^^^^^^^^^^
  [Previous line repeated 997 more times]
RecursionError: maximum recursion depth exceeded

2. Can you create a minimum reproducible example?   
An example model can be downloaded here:
[download model, link verloopt 2025-1-3](https://corporateroot-my.sharepoint.com/:u:/g/personal/wouter_swierstra_rhdhv_com/EV0ZcNhA0P1LuZHTnXoPGtMB_CxAeWkEOH5Yc7drlkSs1w?e=hJwNd0)

Als je het model uitpakt run fix_path.exe om alle paden (oa in PRJ files) goed te zetten:
- Model_Bugmelding\FixPaths.bat

Zonder HFB kan het model doorgerekend worden met iMOD python. Run hiervoor onderstaande 2 batch files. N.B. dit werkt.
- Model_Bugmelding\RUNFILES\BASIS1\BASIS1_STAT-MF6-imodpython\01 CreateINI.bat
- Model_Bugmelding\RUNFILES\BASIS1\BASIS1_STAT-MF6-imodpython\02 RUN MODEL.bat ( 
        - in deze batch wel de verwijzing naar python installatie goed zetten

Met HFB rekent het model niet met iMOD python. Run hiervoor onderstaande 2 batch files. N.B. dit werkt niet.
- Model_Bugmelding\RUNFILES\BASIS1\BASIS1_STAT-MF6-HFB-imodpython\01 CreateINI.bat
- Model_Bugmelding\RUNFILES\BASIS1\BASIS1_STAT-MF6-HFB-imodpython\02 RUN MODEL.bat
         - in deze batch wel de verwijzing naar python installatie goed zetten

Om het model met iMOD5 door te rekenen (inclusief de HFB) N.B. dit werkt.
- Model_Bugmelding\RUNFILES\BASIS1\BASIS1_STAT-MF6\01 runmodel-PRJ MF6.bat

Let op 
als je het model met iMOD5 runt komen de resulten te staan in Model_Bugmelding\RESULTS
De iMOD python berekeningen worden in een folder RESULTS weggeschreven op de locatie waar de berekening ook aangeroepen wordt.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - iMOD Python Version 0.18.1

**Additional context** 
Add any other context about the problem here. The more information you can
provide us, the quicker we respond and fix the problem.

**Comment by JoerivanEngelen** [comment]
Thanks for the reproducible example! @Manangka tackled this and it should be fixed by https://github.com/Deltares/imod-python/pull/1327. I'll leave the issue open for now until either one of us has verified that the provided example is also fixed by this PR.

**Comment by JoerivanEngelen** [comment]
I've tried running the code with the latest fixes, which improved things, but still some things are missing to run the code without error, I've made separate subissues for that, which I added to this issue.
