### ISSUE TITLE
Documentation is based off master; releases lag behind

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#141]
In GitLab by @Huite on Oct 26, 2020, 17:37

As the title mentions, the documentation is currently based off master.

This is obviously not ideal; @visr, I think we've looked at multiple versions before, but that required a rather dubious version of sphinx I think?

At the least we should probably include a tip in the installation section (or something) that there's a real risk of this happening, and that a "solution" is updating.

Alternatively, make sure we're very strict with regards to experimentation on master at all and go with a rolling release?

**Comment by Manangka** [comment]
In GitLab by @visr on Oct 26, 2020, 20:02

Yeah I removed the versioned docs in 3bdde8dd7332646a402c925f3b3bf6cf1560a351 since the extension was not maintained and did not work on modern Sphinx versions. It seems the situation has not yet changed.

In general I agree that we should only put things on master that we are relatively sure we want to release.

We could also start making use of directives like `versionadded` more, see https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html, and possibly put master there for unreleased things. Though then we of course need to update that list before we do a new release. Ideally master will always be in a state that we can drop a release whenever we want.

**Comment by JoerivanEngelen** [comment]
This is not the case anymore, we are rendering the docs now upon releasing. This will be finalized in this PR: https://github.com/Deltares/imod-python/pull/855
