### ISSUE TITLE
Regridder complains about cellsize of layer? & Recheck logic for integer coordinates

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#152]
In GitLab by @Huite on Jan 28, 2021, 15:04

There appears to be a case where the input to a regridding step is chunked by layer.
In this case, the chunked regridding will select a single layer at a time. However, even though the layer is not a regridding dimension it ended up giving an error stating that cellsize has to be defined in case of a coordinate array of size 1.

I'm not sure where this occurs yet: in determining the regrid dimensions, or during the (chunked) regridding step.
If it's the first, it might be smartest to special case integer types like layers: they do not contain spatial coordinates (like a x, y, or z does). In this particular case, calling `.compute()` first apparently solves the issue, so it seems like it's in the regridding step, since inspection of the coordinate does not happen in chunk for determining regridding dims.

This raises another possible issue: if a dataset contains layers [1, 3, 5], the regridder will aggregate over the input layers?
Which doesn't seem desirable!

**Comment by Manangka** [comment]
In GitLab by @tomvansteijn1 on Mar 29, 2023, 11:56

Encountered this issue as well which I hope can be resolved. Simple use case: two steady-state model runs result in two sets of heads (1 IDF file per layer, time = 'steady-state'). Attempt to regrid one set of heads, in order to subtract one from the other, fails due to this error (`ValueError: DataArray has size 1 along time, so cellsize must be provided as a coordinate.`).

This fails:

```
h0 = imod.idf.open(r"..\..\..\head\head*.idf")
h1 = imod.idf.open(r"..\..\..\head\head*.idf")

rgr = imod.prepare.Regridder(method="mean")
rgr.regrid(h0, like=h1)
```

Possible fix:

```
h1 = h1.assign_coords(dtime=1., dlayer=1)
h0 = h0.assign_coords(dtime=1., dlayer=1)

rgr = imod.prepare.Regridder(method="mean")
rgr.regrid(h0, like=h1)
```

I did not try calling compute first.

**Comment by JoerivanEngelen** [comment]
The regridder in iMOD Python is deprecated and is planned to be removed in the v1.0 release.

[Use the xugrid regridder for single arrays](https://deltares.github.io/xugrid/examples/regridder_overview.html)
[Or use iMOD Python to regrid entire MODFLOW6 simulations and packages](https://deltares.github.io/imod-python/user-guide/08-regridding.html)
