### ISSUE TITLE
mf6.open_cbc does not return the right lower face face in a 2D(layer, x) model?

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#159]
In GitLab by @Huite on Mar 7, 2021, 21:34

Checking the result of a 2D example, I'm getting 0 values in the lower face flow, while I have only one row defined.
I didn't test the `_dis_indices` function for 2D arrays, it might not be returning the right numbers here ...

**Comment by Manangka** [comment]
In GitLab by @Huite on Jun 17, 2021, 09:19

Solution requires passing the shape of the arrays (nlay, nrow, ncol) from the grb file to this function.

**Comment by JoerivanEngelen** [comment]
Fixed in #1243
