### ISSUE TITLE
Regridding/voxelizing: Incomplete overlaps can result in wrong or undesirable results

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#161]
In GitLab by @Huite on Mar 18, 2021, 17:20

I've just come across a case where a voxelizer transform value from two cells to a single cell. In this particular case, the destination cell ranges from -60 to -65 m. The source cells only to -63 m; first cell something like -40 to -62, final cell from -62 to -63.

In this case, the voxelizer will compute two overlaps: 2m and 1m.
So far, so good. However, this ends up going wrong for e.g. the calculation of a vertical conductivity, where one would use a harmonic mean. In this case the answer would be (2 + 1) / (2 / kv1 + 1 / kv2), which is then returned for the destination cell.

This is especially undesirable for resistances. In this case, the computed kv value is valid for the entire 5 m, which results in an increased resistance. For example, k in m/d:

```
source:    destination:
+----+     +----+
|1e1 |     |    |
|    |     |    |
+----+     |    |
|1e-3|     |    |
+----+     |    |
           |    |
           +----+
``` 

In this case the sum resistance = (2 / 10) + (1 / 0.001) = 1002 d

With a harmonic mean, the kv becomes 3 / 1002 = 0.00299

However, if we assign this to the destination cell of 5 m; the new resistance becomes 5 / 0.00299 =  1672 days; which is obviously not the same as the original resistance.

While this strictly predictable, it's feels like a real footgun to me. It might be better to default to nan in these cases (if the original domain doesn't stretch all the way). In that case, it's clearly communicated that you consciously have to do a nearest neighbor fill, of choose a fill value...

(This generally only occurs near the top or a bottom of a dataset.)

**Comment by JoerivanEngelen** [comment]
The regridder in iMOD Python is deprecated and is planned to be removed in the v1.0 release.

[Use the xugrid regridder for single arrays](https://deltares.github.io/xugrid/examples/regridder_overview.html)
[Or use iMOD Python to regrid entire MODFLOW6 simulations and packages](https://deltares.github.io/imod-python/user-guide/08-regridding.html)

**Comment by Huite** [comment]
This issue might still pop up with the new regridder though. Might be worth making a note somewhere..
