### ISSUE TITLE
Regridder: clarify inner workings of method

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#172]
In GitLab by @Huite on May 7, 2021, 14:38

There are a number of "default" methods available via strings ("mean", "mode", "sum", etc) for the regridder.
Some of these are weighted by spatial overlap (mean), others are not (sum). There is no way to discover this, apart from reading the source code. The best location for this is likely a user guide, not the API (although the API should link to the user guide).

**Comment by JoerivanEngelen** [comment]
The regridder in iMOD Python is deprecated and is planned to be removed in the v1.0 release.

[Use the xugrid regridder for single arrays](https://deltares.github.io/xugrid/examples/regridder_overview.html)
[Or use iMOD Python to regrid entire MODFLOW6 simulations and packages](https://deltares.github.io/imod-python/user-guide/08-regridding.html)
