### ISSUE TITLE
Regridder: introduce tolerance for tiny overlaps

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#173]
In GitLab by @Huite on May 7, 2021, 14:45

Concrete example, coordinates that fall within the following bounding box:

w, e, n, s
(115000.0, 125000.00000000745, 488100.0000000037, 479100.0000000037)

The parts after the decimal in this case lead to extremely small overlaps. Furthermore, a general case can be made that floating precision may, at any point, generate tiny non-zero overlaps. The area weighted methods of the regridder are somewhat robust to this: tiny overlap -> tiny weight -> tiny effect on aggregated result. For a method such as "sum", however, every value counts equally.

A fairly convenient solution would be including a `tolerance` keyword in the `Regridder.__init__` (with a small default value).
-- its interpretation depending on `ndim_regrid`, 1: length, 2: area, 3: volume (which should be straightforward enough).

**Comment by JoerivanEngelen** [comment]
The regridder in iMOD Python is deprecated and is planned to be removed in the v1.0 release.

[Use the xugrid regridder for single arrays](https://deltares.github.io/xugrid/examples/regridder_overview.html)
[Or use iMOD Python to regrid entire MODFLOW6 simulations and packages](https://deltares.github.io/imod-python/user-guide/08-regridding.html)
