### ISSUE TITLE
Regridder: Source grid not clipped if _is_subset == True

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#174]
In GitLab by @JoerivanEngelen on May 12, 2021, 11:15

If the dimensions of the like are a subset of the source dimensions, 
the dimension is "matching" and nothing is done to the source dimension.
@FransRoelofsen and myself assumed the dimension of source would be clipped if `common._is_subset(a1, a2) == True`

Without this feature, the user has to manually check if `common._is_subset(a1, a2) == True`, 
and clip if needed. Currently this is a module's private function, so hidden to the user.

The use case for this is to create a script that converts an exisiting iMOD model to netcdfs with matching grids, 
and is agnostic of matching grids or not. 

Minimum reproducible example (could be used for test later), both assertions should be True. 
Currently the second one is False.

```python
import imod
import xarray as xr
import numpy as np

xmin, xmax, ymin, ymax = 1, 9, 2, 10
dx = 1.0
dy = -1.0

x = np.arange(xmin, xmax) + dx / 2
y = np.arange(ymin, ymax)[::-1] + dy / 2

shape = (y.size, x.size)

source = xr.DataArray(
    np.ones(shape), coords={"x": x, "y": y, "dx": dx, "dy": dy}, dims=("y", "x")
)
like_match = xr.DataArray(
    np.ones((2, 2)),
    coords={"x": x[3:5], "y": y[3:5], "dx": dx, "dy": dy},
    dims=("y", "x"),
)
like_nomatch = xr.DataArray(
    np.ones((2, 2)),
    coords={"x": x[3:5] + 0.3, "y": y[3:5] - 0.3, "dx": dx, "dy": dy},
    dims=("y", "x"),
)

regridder = imod.prepare.Regridder("sum")

regridded_match = regridder.regrid(source, like_match)
regridded_nomatch = regridder.regrid(source, like_nomatch)

assert regridded_nomatch.shape == like_nomatch.shape
assert regridded_match.shape == like_match.shape
```

**Comment by Manangka** [comment]
In GitLab by @Huite on May 17, 2021, 09:44

If the coordinates are a subset, it shouldn't regrid indeed, it should just do a selection with `.sel` (or `.isel`).
That was my design originally, but I might've changed some things and broken something somewhere ...

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on May 17, 2021, 17:18

Yes, I think that is the expected behaviour, with one nitpick/remark to your comment: 
You refer to cell sizes, but cell sizes alone do not make a similar grid if there is an offset to the coordinates. 
It's about matching coordinates. 

In the example, `like_nomatch` has the same cellsize, but an offset of 0.3. 
In this case the error does not occur.

**Comment by JoerivanEngelen** [comment]
The regridder in iMOD Python is deprecated and is planned to be removed in the v1.0 release.

[Use the xugrid regridder for single arrays](https://deltares.github.io/xugrid/examples/regridder_overview.html)
[Or use iMOD Python to regrid entire MODFLOW6 simulations and packages](https://deltares.github.io/imod-python/user-guide/08-regridding.html)
