### ISSUE TITLE
GDAL requires x axis and y axis attributes on (structured) netCDFs

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#217]
In GitLab by @Huite on Dec 21, 2021, 21:19

Higher versions of GDAL, e.g. 3.4, need the axis X and axis Y attributes, see e.g. Wflow.jl IO:

https://github.com/Deltares/Wflow.jl/blob/9165674957a618cdea9c6962f2749fd97b6f9570/src/io.jl#L413

```
            attrib = [
                "_FillValue" => NaN,
                "long_name" => "x coordinate of projection",
                "standard_name" => "projection_x_coordinate",
                "axis" => "X",
                "units" => "m",
            ],
```

**Comment by Huite** [comment]
The _FillValue should probably be omitted by the way, it causes some trouble if I recall correctly.

And coordinates won't have FillValues anyway.

**Comment by JoerivanEngelen** [comment]
Closed in https://github.com/Deltares/imod-python/pull/1033
