### ISSUE TITLE
Add example to convert an existing 'vanilla' Modflow 2005 model

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#225]
In GitLab by @JoerivanEngelen on Feb 7, 2022, 10:47

People who want to transition to the iMOD Suite might have an existing Modflow 2005 model, the 'vanilla' USGS version, that is.

This model can be read using Flopy and consequently be written to a iMODFLOW or Modflow6 model using iMOD Python.
An example of this in either the iMOD Suite documentation or the iMOD Python documentation, would be very useful.
I posted a near identical issue on [the iMOD Suite documentation Github repository.](https://github.com/Deltares/iMOD-Documentation/issues/7)

@tessodk had an existing modflow 2005 model and conversion script. If the model is not too large, we could nearly directly include it in our example section (Parts of the code probably need some extra explanation or some cleaning up).

**Comment by JoerivanEngelen** [comment]
I think this became irrelevant, since most users will be migrating to Modflow 6.
