### ISSUE TITLE
Add regrid_like method to MetaSWAP object

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#365]
In GitLab by @JoerivanEngelen on May 15, 2023, 17:16

New from the Modflow 6 implementation is that we have to regrid integer arrays, which probably requires some thinking (Downscaling with "nearest", upscaling with "count"?).

Refinement
-------------
- For testing, ideally, this would be used https://github.com/Deltares/imod-python/issues/971
- For now, we can use test script, also described in that issue or juste purely unit test if files are written as expected.,
- Ideally, we work towards using a shared base class between Modflow 6 Model and MetaSWAP model
- Has to be investigated if feasable, we can implement and duplicate code where necessary.

Update:
----------
After working on this issue, the scope has been reduced and new issues will be created to address the remaining parts.
The new scope is:
-implement regridding for "easy"packages, specifically 
      -Infiltration
      -Initial conditions
      -LandUse
      -Ponding
      -ScalingFactors
      -Vegetation
-add tests for regridding these packagews

**Comment by JoerivanEngelen** [comment]
Update:

We do not add regridding to MetaMod, as this would entail chaning things in primod, I think we can ask from users to initiate the MetaMod object again after regridding their Modflow6 simulation and MetaSWAP model.

**Comment by JoerivanEngelen** [comment]
Task done, merged into: https://github.com/Deltares/imod-python/tree/metaswap_regridding_feature_branch
