### ISSUE TITLE
Add clipping method to MetaMod model

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#444]
In GitLab by @JoerivanEngelen on Jun 26, 2023, 11:23

Add clipping method to MetaSWAP model object and MetaMod object.

MetaSWAP requires has no lateral flow, so no special boundary conditions are required at the clipped model's edges.

**Comment by JoerivanEngelen** [comment]
This would entail fixing things in primod, I think we can ask from users to initiate the MetaMod object again after clipping their Modflow6 simulation and MetaSWAP model.
