### ISSUE TITLE
disv_converter: CHD package, different systems defined for every layer

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#474]
In GitLab by @JoerivanEngelen on Jul 14, 2023, 14:17

[!240 (diffs)](https://gitlab.com/deltares/imod/imod-python/-/merge_requests/240/diffs)

CHDs are separated into different systems for each layer

**Comment by JoerivanEngelen** [comment]
The disv_converter is likely going to be removed in v1.0.
