### ISSUE TITLE
disv_converter: Broadcasting bug with well package

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#475]
In GitLab by @JoerivanEngelen on Jul 14, 2023, 14:18

[See example here](https://gitlab.com/deltares/imod/imod-python/-/merge_requests/240/diffs)

Due to a bug with broadcasting n_times too many wells are generated:
94 times & 94 indices.

**Comment by JoerivanEngelen** [comment]
The disv_converter is likely going to be removed in v1.0.
