### ISSUE TITLE
Create logging interface

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#490]
In GitLab by @JoerivanEngelen on Jul 25, 2023, 17:33

Create a simple logging interface which can be used (in the follow-up tasks) e.g. to :

* To log at package writing and dumping
* To log at simulating writing and dumping
* Validation
* Time Discretization
* Things happening with Grid Agnostic packages behind the scenes (e.g. removing invalid wells)
* regridding/clipping/masking

We should apply [Loguru](https://github.com/Delgan/loguru) here, as it:

* doesn't require much code
* is well maintained
* most-popular third-party logging package
* Also used in iMOD Coupler, so the product line has experience.

- [x] #751
- [x] #752

**Comment by JoerivanEngelen** [comment]
Merged in https://github.com/Deltares/imod-python/pull/754
