### ISSUE TITLE
Test and update running examples for release 0.14.0

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#495]
In GitLab by @JoerivanEngelen on Jul 27, 2023, 15:03

We have created a different Well and Horizontal Flow Barrier package, test if the existing examples still work and update them if they still contain ``WellDisVertices`` or ``WellDisStructured`` package

### Tasks
- [x] https://github.com/Deltares/imod-python/issues/586

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on Jul 27, 2023, 16:11

marked this issue as blocked by #381

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on Sep 7, 2023, 13:00

There is still an example using the old Well package:

https://deltares.gitlab.io/imod/imod-python/examples/mf6/Henry.html

**Comment by Manangka** [comment]
added #586 as child task

**Comment by JoerivanEngelen** [comment]
Fixed in https://github.com/Deltares/imod-python/pull/1081
