### ISSUE TITLE
Decide whether to prioritize refactoring to grid agnostic packages or to take similar approach as disv_converter

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#500]
In GitLab by @JoerivanEngelen on Aug 1, 2023, 17:52

iMOD 5 projectfile data can be defined on grids with a different cellsize and extent. iMODFLOW regrids this to a single grid behind the scenes. Since we don't have a "Model Grid Agnostic" model object yet (which would be very handy for this), [see milestone](https://gitlab.com/deltares/imod/imod-python/-/milestones/7#tab-issues), we might have to regrid to a consistent grid for the Modflow6 object first.
It is good to investigate what would be preferable: A short-term solution for quick testing of the functionality or a long-term which would allows us to easily implement functionality for reading native Modflow 6 files as well.

**Comment by JoerivanEngelen** [comment]
We are working on an implementation, so far we require no "grid-agnostic-grid" object
