### ISSUE TITLE
Fix MyPy errors in mf6 module

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#563]
At the moment MyPy reports more than 100 issues in the imod/mf6 folder. We need to resolve them and change the pipeline from giving a warning to giving an error when new MyPy errors are reported

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on Oct 26, 2023, 10:55

marked this issue as related to #65

**Comment by JoerivanEngelen** [comment]
Some work on this has been done in: https://github.com/Deltares/imod-python/issues/681, https://github.com/Deltares/imod-python/issues/682, https://github.com/Deltares/imod-python/issues/684

**Comment by JoerivanEngelen** [comment]
Issue description referred to mf6 module, is fixed now.
