### ISSUE TITLE
Enable support for Newton-Raphson

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#564]
Newton support has been restored as part of #582

However before we should consider the following:

- Add validation. The combination of settings required and cells types are important
- We need to propagate the setting to the GWFGWF exchange files (Do other packages also need it?)

**Comment by Manangka** [comment]
marked this issue as blocking #549

**Comment by JoerivanEngelen** [comment]
Most of the work for this is done, work will be continued further in https://github.com/Deltares/imod-python/issues/724
