### ISSUE TITLE
Transition the CI pipeline to TeamCity

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#576]
Regardless of the transition to Github the CI pipeline can be migrated to TeamCity. Gitlab as well as Github support it. If we would switch to TeamCity then that might easing our transition to GitHub

* create empty teamcity project
* make sure teamcity gets the right python installation on the agent. It should always install it fresh and this is what we need Julian for. 
* convert gitlab ci script to teamcity script ( powershell(?))
* connect to gitlab: gitlab should start teamcity and wait for it 
* teamcity should run the examples
* How is the documentation published on gitlab? Should teamcity make the documentation 

Note: involve @Hofer-Julian  and Robert

**Comment by JoerivanEngelen** [comment]
Done

![image](https://github.com/Deltares/imod-python/assets/9744750/05aa137b-14c0-4617-97bc-7bb7d9f9dc8a)

https://github.com/Deltares/imod-python/issues/575
