### ISSUE TITLE
after splitting a simulation, the simulation cannot be written to file anymore

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#578]
In GitLab by @luitjansl on Oct 12, 2023, 10:41

if we have a simulation object and call "split" on it, then the split function returns a new simulation. The original simulation should still be usable, but calling "write" on it produces an error. In pseudocode:

simulation_A = create_some_simulation()

simulation_B = simulation_A.split(label_array)

simulation_A.write(...) #produces error

Note:
It happens also without splitting. Calling the write method twice causes the same issue

Refinement
-------------
- debug until source of the error has been found
- possible mutations to original object: 
    - GWF-GWT exchange packages are added during the write method.
    - Any other mutations done during writing?
    - Any other mutations done during splitting?
- Add test:
    - Copy simulation A
    - Split simulation A
    - Simulation A should be equal to its copy

**Comment by Manangka** [comment]
In GitLab by @luitjansl on Oct 12, 2023, 10:41

added #538 as parent issue

**Comment by Manangka** [comment]
removed parent issue #538

**Comment by Manangka** [comment]
changed type from task to issue

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on Nov 7, 2023, 10:02

marked this issue as related to #601

**Comment by JoerivanEngelen** [comment]
Might be somewhat relevant: https://stackoverflow.com/questions/39606315/what-is-the-python-equivalent-of-c-const-reference-copy-constructor-arguments
