### ISSUE TITLE
Support multiple HFB in the same layer

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#591]
Horizontal flow barriers are created by defining the barrier's geometry (line segments) and assigning values to them (resistance, multiplier, etc.). In an internal step the line segments are snapped to a cell edge. This snapping happens in one go for all the line segments. This has the following short comings:
- If 2 barriers cross the same edge and lay in different layers then we can't distinguish them and only the value of the last barrier will be applied
- If 2 barriers cross the same edge and share the same layer then an effective value should be computed but in the current implementation only the value of the last defined barriers is applied

As I user I want to be able to define multiple barriers that cross the same edge and take into consideration the layer it belongs to (i.e. compute a effective resistance where the values of all barriers are taken into account)

Worst case: 3 overlay each other, resistances should be summed.

Pragmatic fix within iMOD Python:

* We can easily snap to grid for each linestring, to improve performance we could consider clipping the grid based on the bounding box. Then mapping this back to the original grid

Better fix ``xugrid``:

* Fix within xugrid: For each segment create mapping with fractions of overlap for each edge. This is related to: https://github.com/Deltares/xugrid/issues/136 . The difference here is that this overlap should be computed for each segment instead of each linestring.

### Tasks
- [ ] https://github.com/Deltares/imod-python/issues/631

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on Nov 7, 2023, 11:54

added #631 as child task

**Comment by JoerivanEngelen** [comment]
Implemented in https://github.com/Deltares/imod-python/pull/1093
