### ISSUE TITLE
Cleanup utilities part 1

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#622]
In GitLab by @JoerivanEngelen on Nov 3, 2023, 11:17

Currently we have an ``imod.util``, ``imod.wq.timeutil``, ``imod.mf6.utilities``. 

There are multiple issues with the current state:

- It is a mix of utilities which are used internally and which are useful for users. 
- ``imod.util`` contains utilities for handling time, space, and paths. I think we can split this up into separate utilities.
- ``imod.wq.timeutil`` contains useful utilities which are also used in the ``mf6`` and ``flow`` module. So these can be moved one level up.

The first step is: to create topical utilities: ``imod.util.grid``, ``imod.util.paths``, ``imod.util.time``. In the ``util/__init__.py`` we can expose utilities which are useful for users as well (and maintain backwards compatibility).

**Comment by JoerivanEngelen** [comment]
Related to https://github.com/Deltares/imod-python/issues/542
