### ISSUE TITLE
Unclear docstring in Well-class on variable ‘rate’ for transient cases

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#627]
In GitLab by @HendrikKok on Nov 7, 2023, 10:28

This should not be a list of floats, but dataset with index and time?

**Comment by JoerivanEngelen** [comment]
If I'm not mistaken, both are allowed. If list of floats, extraction is constant through time. If dataarray with index and time as dimensions, the extraction rate varies through time.
