### ISSUE TITLE
Regridding Hondsrug example: Make sure Validation can be turned on when writing

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#650]
In GitLab by @JoerivanEngelen on Nov 17, 2023, 14:34

The validation is turned off now in the example. This results in errors like:

https://gitlab.com/deltares/imod/imod-python/-/work_items/638

**Comment by JoerivanEngelen** [comment]
Fixed at some point:
https://deltares.github.io/imod-python/examples/mf6/different_ways_to_regrid_models.html
