### ISSUE TITLE
Expand mask method in partitioning examples

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#651]
In GitLab by @JoerivanEngelen on Nov 17, 2023, 14:39

Stems from https://gitlab.com/deltares/imod/imod-python/-/work_items/641

When setting up tests for partitioning, we sometimes wish to make cells inactive in a model. This means that those cells must be made inactive in the model's idomain array, and then data associated to those cells must be removed from all packages in the model.  We would like to use the "mask" method for that, but that doesn't work - after masking all the packages, we still get validation errors when writing the simulation. 

Currently the packages are masked in a loop:

```python
    # deactivate some cells on idomain
    idomain = simulation["GWF_1"].domain
    deactivated_cells = slice(93, 101)
    idomain.loc[{"mesh2d_nFaces": deactivated_cells}] = 0

    # The cells we just deactivated on idomain must be deactivated on package inputs too.    
    for name, package in simulation["GWF_1"].items():
        if not isinstance(package, Well):
            for arrayname in package.dataset.keys():
                if "mesh2d_nFaces" in package[arrayname].coords:
                    if np.issubdtype(package[arrayname].dtype, float):
                        mask_value = np.nan
                    else:
                        mask_value = 0
                    package[arrayname].loc[{"mesh2d_nFaces": deactivated_cells}] = mask_value
```

But ideally we would like to use the (now private) `_mask_all_packages`  function of "model" for that

Refinement
-------------
- Make private method ``_mask_all_packages`` public
- Update example
- Update test/fixtures where this is also done.
- If masking results in empty packages, remove them
- Add Validation for when all values are accidentily deactivated

**Comment by luitjansl** [comment]
merged to master
