### ISSUE TITLE
Make options like "save_flows" configurable for high level well packages

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#652]
In GitLab by @JoerivanEngelen on Nov 17, 2023, 14:44

Created from: https://gitlab.com/deltares/imod/imod-python/-/work_items/623

Currently unable to use options like ``save_flows``. Therefore, save_flows was hardcoded in the jinja template in the featurebranch, which is unwanted. 

The user should be able to pass settings for high-level packages.

**Comment by JoerivanEngelen** [comment]
Update these settings are passed on to the Well package at the current state of the codebase, but not to the HorizontalFlowBarrier packages yet.
