### ISSUE TITLE
imod.mf6.out.open_cbc does not seem to be able to open unstructured with inactive cells

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#669]
In GitLab by @JoerivanEngelen on Nov 25, 2023, 16:53

As the title says. 

This showed up when trying to open the the budgets in ``test_partitioning_unstructured_with_inactive_cells`` and ``test_partitioning_unstructured_with_vpt_cells``. So to reproduce, add this in these tests:

```
orig_cbc = imod.mf6.open_cbc(
    orig_dir / "GWF_1/GWF_1.cbc",
    orig_dir / "GWF_1/disv.disv.grb",
)
```

This will throw an IndexError. Probably some masking/filtering of inactive/vertical passthrough cells is missing/failing. Interestingly, the open_hds doesn't seem to have any trouble with this.

**Comment by luitjansl** [comment]
update: the tests mentioned `test_partitioning_unstructured_with_inactive_cells` and `test_partitioning_unstructured_with_vpt_cells` have been merged, and now `test_partitioning_unstructured_with_inactive_cells`  is done twice- first marking some cells as inactive (0) and then marking these cells as vpt (-1). 
In both cases, the transport budget can be loaded using  `transport_budget = simulation.open_transport_budget(species)`
