### ISSUE TITLE
imod.idf.open() crashes when optional Dask dependency is missing

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#671]
In GitLab by @HendrikKok on Nov 28, 2023, 11:54

The open method should raise an error or read all data to memory, if Dask dependency is missing.

**Comment by JoerivanEngelen** [comment]
Hi @HendrikKok . Thanks for creating the issue. I think some confusion is going on here: Dask is a required dependency for iMOD Python. For example, in the ``pyproject.toml``, it is listed under ``dependencies``, together with ``numpy``, ``pandas`` etc, not ``optional-dependencies``. 

I'm wondering what gave you the impression that ``dask`` is an optional dependency. It could be that the documentation is unclear about this somewhere. To be fair, we don't list required and optional packages explicitly anywhere in the documentation. If  you could help us provide more clarity on this with some ideas in a comment, that'd be much appreciated! 

For now, I'm closing this issue, feel free to re-open if you think it is not resolved.
