### ISSUE TITLE
Implement HorizontalFlowBarrier with varying zbot and ztop.

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#678]
In GitLab by @JoerivanEngelen on Dec 5, 2023, 13:06

Taken from: https://gitlab.com/deltares/imod/imod-python/-/issues/556

> The current horizontal flow barrier uses a ztop and zbottom, which are scalar values for linestrings. 
> However, a linestring generally consists of many line pieces, which have their own z values.
>
> There is room to support this, via 3D shapely geometries (which is incidentally what my originally 
> implementation used: https://gitlab.com/deltares/imod/imod-python/-/blame/c162ab315507745aec7ea3ee6cc46103626bed7a/imod/formats/prj/disv_conversion.py#L660)

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on Dec 5, 2023, 13:07

marked this issue as related to #556

**Comment by JoerivanEngelen** [comment]
Implemented in https://github.com/Deltares/imod-python/pull/1100
