### ISSUE TITLE
unstructured grids: label array has effect on merged solution

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#685]
In GitLab by @luitjansl on Dec 11, 2023, 11:27

We would expect that after partitioning a simulation in different ways, running the simulation and merging the heads, we would get the same merged heads regardless of what label-array was used for partitioning. But this is not the case. 

To reproduce look at test "test_partitioning_unstructured_with_inactive_cells". It currently uses has a case with 2 partitions and a case with 3 partitions. Add  a third case which is the inverse of the 2 partition case. Add the following to function setup_partitioning_arrays:

```python
    two_parts_inverse = zeros_like(idomain_top)
    two_parts_inverse.values[:108] = 1
    two_parts_inverse.values[108:] = 0

    result["two_parts_inverse"] = two_parts_inverse
```

and parameterize test "test_partitioning_unstructured_with_inactive_cells" to use this label array as well. With this partition, the tolerance checks at the end of the test fail.

**Comment by luitjansl** [comment]
could not be reproduced. Most likely, the reindexing that is now done after loading the split head results fixes this issue.

**Comment by JoerivanEngelen** [comment]
I think this is indeed fixed by the reindexing
