### ISSUE TITLE
Research/ask if extra cell exchanges are required for XT3D

### ISSUE THREAD

**Issue by JoerivanEngelen** [Deltares/imod-python#744]
XT3D also takes the diagonally surrounding cells into account. We have to find out if these diagonal connections have to be added to the exchange files. @mjr-deltares might be able to answer this.

**Comment by mjr-deltares** [comment]
Hi @JoerivanEngelen , no, only the primary connection should be specified in the exchange.

**Comment by JoerivanEngelen** [comment]
Thanks, that saves us a lot of work! :-) 

Good to know that XT3D makes a distinction between primary and secondary connections
