### ISSUE TITLE
separate pipeline for modflow's nightly build ?

### ISSUE THREAD

**Issue by luitjansl** [Deltares/imod-python#757]
sometimes we are interested in using features or fixes only present in the nightly build of MF6 (for example to obtain correct CHD fluxes at partition boundaries).
We should be able to use it for testing purposes in the pipeline, but currently some transport tests fail with it. 

We should address this, and  in such a manner that we don't loose support for the last stable release. Perhaps a separate pipeline for each MF6 version?

**Comment by JoerivanEngelen** [comment]
Blocked by https://github.com/Deltares/imod-python/issues/748

**Comment by JoerivanEngelen** [comment]
As discussed with @luitjansl and @Manangka, we prefer the following solution:

- We can keep the build pipeline that is triggered by PRs the same
- Separate nightly build against nightly MODFLOW 6 build on TeamCity
- If nightly build fails, developers are warned via e-mail
