### ISSUE TITLE
Key "solver" is hardcoded in simulation.split

### ISSUE THREAD

**Issue by JoerivanEngelen** [Deltares/imod-python#778]
In de ``Modflow6Simulation.split`` method we hardcode the "solver" key for the solver. This is wrong, as users are free to assign their solver package to any key. I think only the packages "time_discretization" and exchanges keys can be hardcoded, as they are generated by methods.

Therefore, we should change:

```python
        new_simulation["solver"]["modelnames"] = xr.DataArray(
            list(get_models(new_simulation).keys())
        )
```

to: 

```python
        ims_key = simulation._get_pkgkey("ims")
        new_simulation[ims_key]["modelnames"] = xr.DataArray(
            list(get_models(new_simulation).keys())
        )
```

This requires adding a ``_get_pkgkey`` method to the Modflow6Simulation class as well, or moving the logic to utility function:

```python
get_pkg_key(model_or_simulation, package_type)
```

**Comment by luitjansl** [comment]
The "solver" label was removed in commit of PR 791 which solved issues #788 and #789
