### ISSUE TITLE
Create multi-model solute transport example

### ISSUE THREAD

**Issue by JoerivanEngelen** [Deltares/imod-python#787]
Goal of this example is:
- Test for ourselves if multi-model transport models work
- Showing to our users how to do this

Easiest probably is:
- Convert this model to iMOD Python https://modflow6-examples.readthedocs.io/en/latest/_notebooks/ex-gwt-mt3dms-p03.html
- Partition it to 4 partitions
- Compute

Things to add to example:
- Explanation why separate GWTGWT files for each model, despite same cells connected: settings can be different for each species. For example, advection schemes.

**Comment by luitjansl** [comment]
it was merged to the feature branch.
