### ISSUE TITLE
add function imod.formats.idf.create

### ISSUE THREAD

**Issue by FransRoelofsen** [Deltares/imod-python#790]
For supporting iMOD5 users in adopting iMOD Python (backward compatibility) this idf.create function is helpful (own experience). 
Most important use of such an IDF (DataArray) is in defining an empty IDF to be used as "like" in the function Regridder.

In the past Huite developed a functions already but for private use.  Better sharing it with the community. 
Actual set up of the function: 

def create_idf(xmin, ymin, xmax, ymax, dx, dy, fill_value):
    """
    Creates an IDF file with given extend and cellsize
 
    Parameters
    ----------
    xmin, ymin, xmax, ymax : float
        coordinate
    dx,dy: float
        cell size in specific direction
    fill_value: float
        value to fill in for the complete IDF
    Returns
    -------
    xarray.DataArray
        A float xarray.DataArray with a constant value.
    """
 
    if not dx > 0.0:
        raise ValueError("dx must be positive")
    dy = -abs(dy)
 
    x = np.arange(xmin, xmax, dx) + 0.5 * dx  # dx must be possitive
    y = np.arange(ymax, ymin, dy) + 0.5 * dy  # dy must be possitive
    nrow = y.size
    ncol = x.size
 
    da = xr.DataArray(
        data = np.full((nrow, ncol), fill_value),
        coords = {"y": y, "x": x, "dx": dx, "dy": dy},
        dims = ("y", "x"),
    )
    return da

**Comment by Huite** [comment]
Hi @FransRoelofsen,

These are available under the varies ``util.empty_ `` functions:

https://deltares.github.io/imod-python/api/generated/util/imod.util.empty_2d.html#imod.util.empty_2d
https://deltares.github.io/imod-python/api/generated/util/imod.util.empty_2d_transient.html#imod.util.empty_2d_transient
https://deltares.github.io/imod-python/api/generated/util/imod.util.empty_3d.html#imod.util.empty_3d
https://deltares.github.io/imod-python/api/generated/util/imod.util.empty_3d_transient.html#imod.util.empty_3d_transient

**Comment by JoerivanEngelen** [comment]
Closing for now, if the provided functions do not do what you want, feel free to re-open.
