### ISSUE TITLE
update ssm package when splitting flow + transport simulations

### ISSUE THREAD

**Issue by luitjansl** [Deltares/imod-python#798]
The ssm package is part of a transport model, and it  describes what flow boundaries to take into account for transport. For example:
```
begin options
  save_flows
end options

begin sources
  chd aux species_b
  rch aux species_b
  well aux species_b
end sources
```
But when splitting into subdomains, not every flow boundary will be present in every partition, and this will cause modflow to fail to run the simulation

**Comment by JoerivanEngelen** [comment]
Merged in https://github.com/Deltares/imod-python/pull/819
