### ISSUE TITLE
fix 1d transport test

### ISSUE THREAD

**Issue by luitjansl** [Deltares/imod-python#823]
There was a typo in the comparison statement for split and unsplit model concentrations:
`    np.testing.assert_allclose(
        head.sel(time=2000)["head"].values,
        original_head.sel(time=200).values,
      ...
    )`

both times should be 2000, not 2000 and 200.
This typo lead to unreasonably high tolerance settings to make the test pass.

**Comment by JoerivanEngelen** [comment]
Fixed in #824
