### ISSUE TITLE
mf6 Simulation dump: add axis attributes for x and y attributes to QGIS will draw the netCDFs appropriately

### ISSUE THREAD

**Issue by Huite** [Deltares/imod-python#828]
GDAL requires {"axis": "X"} and {"axis": "Y"} on the x and y coordinates respectively to recognize the x and y coordinates.

Pragmatically, we could add these attributes during the dump.

**Comment by JoerivanEngelen** [comment]
Related somewhat to: https://github.com/Deltares/imod-python/issues/217
