### ISSUE TITLE
mf6 validation: raises false positive on recharge

### ISSUE THREAD

**Issue by Huite** [Deltares/imod-python#830]
I'm getting this error:

```python
		* rch package:
			* rate:
				* data values found at nodata values of idomain
```

While recharge is assigned to layer 1 (though not as a dimension!), and the idomain for layer 1 is fully 1-valued.

```
Recharge
<xarray.Dataset>
Dimensions:        (time: 375, y: 195, x: 210)
Coordinates:
  * time           (time) datetime64[ns] 2020-01-01 2020-01-02 ... 2021-01-09
    dx             float64 ...
    dy             float64 ...
  * y              (y) float64 4.155e+05 4.155e+05 ... 4.107e+05 4.107e+05
  * x              (x) float64 1.718e+05 1.719e+05 ... 1.77e+05 1.771e+05
    layer          int32 ...
Data variables:
    rate           (time, y, x) float64 0.001 0.001 0.001 0.001 ... 0.0 0.0 0.0
    print_input    bool False
    print_flows    bool False
    save_flows     bool False
    observations   object None
    repeat_stress  object None
```

```python
mf6sim = imod.mf6.Modflow6Simulation.from_file(r"clipped/GWF_1.toml")
mf6sim.write("check") # fails with above error

# Add a layer dim
gwf = mf6sim["GWF_1"]
gwf["rch"]["rate"] = gwf["rch"]["rate"].expand_dims("layer").transpose("time", "layer", "y", "x")

mf6sim.write("check") # no longer raises
```

**Comment by Huite** [comment]
I think this check has been added somewhat recently, but it might effectively be a breaking change compared with older versions. If you turn off validation, it writes the model, and MF6 can even run it.

The essential part is that the writing part has logic for dealing with a layer coordinate (which is not a dimension) but the validation code does not use this logic.

This logic is found here: 
https://github.com/Deltares/imod-python/blob/ccebd4e30671ee912b52c37fe1d6c07fe91d381a/imod/mf6/boundary_condition.py#L107

Which then goes into the recarr stuff:
https://github.com/Deltares/imod-python/blob/ccebd4e30671ee912b52c37fe1d6c07fe91d381a/imod/mf6/boundary_condition.py#L19

I'm not overly fond of this logic to be honest. It's worth considering whether a dimension should just be required in this case.

The reasons we went for this originally, I think, is that if you select a single layer with xarray `ds.sel(layer=1)` it will drop the dimension, but not the coordinate. In general, people should do `ds.sel(layer=[1])` instead, since it keeps a 1-sized dimension intact.

**Comment by JoerivanEngelen** [comment]
It could be that the validation for checking whether boundary conditions occur in inactive cells doesn't handle this well.

In the validation upon initialization, we do account for the case you described, by having a ``CoordsSchema`` checking if ``layer`` is located somewhere, and one of the allowed dims being ``("y", "x")``. However, I don't think our test bench contains this case in all validation tests.

**Comment by JoerivanEngelen** [comment]
@tvw11 also ran into this yesterday, I'm picking this up now as multiple people run into this issue.
