### ISSUE TITLE
Add support for API-package of MODFLOW 6

### ISSUE THREAD

**Issue by HendrikKok** [Deltares/imod-python#838]
The API package was created to provide a convenient way to touch MODFLOW 6 internals, outside the package levels. We need this package for the coupling between MODFLOW 6 - Ribasim - MetaSWAP. The package only contains an options and dimensions block. The actual data and nodemapping will be set via the imod_coupler. The minimum input than looks like:

 begin options
 end options
  
 begin dimensions
   MAXBOUND           1
 end dimensions

**Comment by JoerivanEngelen** [comment]
Refinement:
- Add API package, inherit Package object
- Should have the following arguments: maxbound, print_input, save_flows, print_flows
- Jinja template needs to be created
- Test rendering

**Comment by luitjansl** [comment]
How should the API package deal with regridding or partitioning? Should the maxbound be updated automatically on regridding ( and how?) These things would be doable if the api package had a spatial definition- if we knew for what cells information is queried or set using api calls. Would such a spatial definition make sense as a constructor argument?
