### ISSUE TITLE
Github release still mentions gitlab changelog

### ISSUE THREAD

**Issue by Huite** [Deltares/imod-python#858]
https://github.com/Deltares/imod-python/releases/tag/0.15.2 mentions gitlab.io address.

**Comment by JoerivanEngelen** [comment]
Thanks, I think this is a mistake introduced in the new release pipeline. @Manangka could you fix this?

**Comment by Manangka** [comment]
Yes my bad. Will Fix it!

**Comment by Manangka** [comment]
It has been fixed. The new description now points to the correct changelog on github
