### ISSUE TITLE
"loguru" missing in pyproject.toml

### ISSUE THREAD

**Issue by JoerivanEngelen** [Deltares/imod-python#861]
I tried pip install [on Google Colab because of this issue](https://github.com/Deltares/imod-python/issues/860) and ran into an issue: we forgot to add Loguru to the list of dependencies in the pyproject.toml.

For people to fix now, do: 

``pip install loguru``
``pip install imod``

**Comment by Huite** [comment]
Xarray explicitly tests whether it works with the optional dependencies, see:
https://github.com/pydata/xarray/tree/main/ci/requirements

They also mark their tests explicitly. That's rather a lot of work, but we can gain most of the benefit easily, by simply doing a pip install and just checking whether the import succeeds.
