### ISSUE TITLE
Add converter for iMOD5 RCH package

### ISSUE THREAD

**Issue by JoerivanEngelen** [Deltares/imod-python#969]
Needs to:
* Allocate planar recharge rates or constants to uppermost active cells.

Blocked by:
https://github.com/Deltares/imod-python/issues/949

We think boundary conditions always need to be assigned to a active cell, but this can be verified.

**Comment by luitjansl** [comment]
the recharge indeed needs to be assigned to an active cell. Verified  by making some cells VPT in the circle model, this resulted in the following modflow output:
 215.   Cell is outside active grid domain: (1,215)
  216.   Cell is outside active grid domain: (1,216)
  217.          216  errors encountered.

UNIT ERROR REPORT:

  1. Error occurred while reading file
     'C:\Users\slooten\AppData\Local\Temp\pytest-of-slooten\pytest-422\test_si
     mulation_inactive_top0\circle\GWF_1\rch.rch'
