### ISSUE TITLE
The imod.prepare.spatial.celltable method always produces integer values, even if specified columns of polyline are floats. 

### ISSUE THREAD

**Issue by HendrikKok** [Deltares/imod-python#978]
Problem seems to lie in allocating the work-array "values", in the _celltable method. When specifying the correct dtype, its works as expected.

**Comment by JoerivanEngelen** [comment]
@HendrikKok you showed me before that more specifically, the problems lay in the following lines:

```python
    # Pre-allocate work arrays
    values = np.full(alloc_len, 0)
    frequencies = np.full(alloc_len, 0)
```

Which always result in an integer array. I think this can be altered to something like: ``np.zeros(alloc_len).astype(values_type)``

Further investigation with @Huite  revealed that the dtype of ``rasterized`` is also forced to integer:

```python
    rasterized = gdal_rasterize(
        path, column, nodata=nodata, dtype=np.int32, spatial_reference=spatial_reference
    )
```

So to fix: 

* Infer dtype of column in some way
* Set appropriate dtypes of ``values``
* Appropriate dtype for ``rasterized``
